# Generated by Django 3.0.5 on 2020-05-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharinggoods', '0005_content_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, upload_to='sharinggoods/products/%Y/%m/%d'),
        ),
    ]
