# Generated by Django 3.0.6 on 2020-07-03 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharinggoods', '0007_auto_20200704_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
